### 잘 살아있나 확인
GET localhost:8080/hello

### 사용자 생성
POST localhost:8080/users
Content-Type: application/json

{
  "username": "seokmin"
}

### 사용자 목록 보기
GET localhost:8080/users

### 같은 username으로 중복 테스트
POST localhost:8080/users
Content-Type: application/json

{
  "username": "seokmin"
}

### 사용자 추가하기
POST localhost:8080/users
Content-Type: application/json

{
  "username": "hana"
}

### 같은 username으로 중복 테스트(에러 코드 500 -> 400)
POST localhost:8080/users
Content-Type: application/json

{
  "username": "seokmin"
}

### post 정상 작동 확인을 위한 회원 writer1 생성
POST localhost:8080/users
Content-Type: application/json

{
  "username": "writer1"
}

### 생성 확인 id=3
GET localhost:8080/users

### 게시글 작성
POST localhost:8080/posts
Content-Type: application/json

{"userId": 1,
  "title": "첫 글입니다.",
  "content": "안녕하시라무"
}

### 게시글 목록 조회
GET localhost:8080/posts

### 게시글 상세 조회
GET localhost:8080/posts/3

### 게시글 삭제
DELETE localhost:8080/posts/1

### 게시글 수정
PUT localhost:8080/posts/3
Content-Type: application/json

{
  "title": "바보입니다",
  "content": "제 이름은 코난, 명탐정이죠"
}